# Generated by Django 4.2.15 on 2024-08-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Susutype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverytypename', models.CharField(blank=True, db_column='DeliveryTypeName', max_length=150, null=True)),
                ('deliveryusedescription', models.CharField(blank=True, db_column='DeliveryUseDescription', max_length=150, null=True)),
                ('memodeliverynote1', models.CharField(blank=True, db_column='MemoDeliveryNote1', max_length=150, null=True)),
                ('deliveryownerfirstname', models.CharField(blank=True, db_column='DeliveryOwnerFirstName', max_length=150, null=True)),
                ('deliveryownerlastname', models.CharField(blank=True, db_column='DeliveryOwnerLastName', max_length=150, null=True)),
                ('deliveryownerfullname', models.CharField(blank=True, db_column='DeliveryOwnerFullName', max_length=150, null=True)),
                ('deliveryowneremail', models.CharField(blank=True, db_column='DeliveryOwnerEmail', max_length=150, null=True)),
                ('createby', models.CharField(blank=True, db_column='CreateBy', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Susume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionnumber', models.IntegerField(db_column='RegionNumber')),
                ('regions', models.CharField(blank=True, db_column='Regions', max_length=150, null=True)),
                ('deliveryoption', models.CharField(blank=True, db_column='DeliveryOption', max_length=150, null=True)),
                ('currencytype', models.CharField(blank=True, db_column='CurrencyType', max_length=150, null=True)),
                ('defaultfte_year', models.FloatField(db_column='DefaultFTE_Year', default='1795.0')),
                ('workweek', models.FloatField(db_column='WorkWeek', default='40.0')),
                ('deliveryctrcostfactor', models.FloatField(db_column='DeliveryCtrCostFactor', default='1.0')),
                ('band2', models.FloatField(db_column='Band2', default='0.0')),
                ('band2name', models.CharField(blank=True, db_column='Band2Name', default='Band #2', max_length=150, null=True)),
                ('band2count', models.FloatField(db_column='Band2Count', default='0.0')),
                ('band2percentage', models.FloatField(db_column='Band2Percentage', default='0.0')),
                ('band3', models.FloatField(db_column='Band3', default='0.0')),
                ('band3name', models.CharField(blank=True, db_column='Band3Name', default='Band #3', max_length=150, null=True)),
                ('band3count', models.FloatField(db_column='Band3Count', default='0.0')),
                ('band3percentage', models.FloatField(db_column='Band3Percentage', default='0.0')),
                ('band4', models.FloatField(db_column='Band4', default='0.0')),
                ('band4name', models.CharField(blank=True, db_column='Band4Name', default='Band #4', max_length=150, null=True)),
                ('band4count', models.FloatField(db_column='Band4Count', default='0.0')),
                ('band4percentage', models.FloatField(db_column='Band4Percentage', default='0.0')),
                ('band5', models.FloatField(db_column='Band5', default='0.0')),
                ('band5name', models.CharField(blank=True, db_column='Band5Name', default='Band #5', max_length=150, null=True)),
                ('band5count', models.FloatField(db_column='Band5Count', default='0.0')),
                ('band5percentage', models.FloatField(db_column='Band5Percentage', default='0.0')),
                ('band6', models.FloatField(db_column='Band6', default='0.0')),
                ('band6name', models.CharField(blank=True, db_column='Band6Name', default='Band #6', max_length=150, null=True)),
                ('band6count', models.FloatField(db_column='Band6Count', default='0.0')),
                ('band6percentage', models.FloatField(db_column='Band6Percentage', default='0.0')),
                ('band7', models.FloatField(db_column='Band7', default='0.0')),
                ('band7name', models.CharField(blank=True, db_column='Band7Name', default='Band #7', max_length=150, null=True)),
                ('band7count', models.FloatField(db_column='Band7Count', default='0.0')),
                ('band7percentage', models.FloatField(db_column='Band7Percentage', default='0.0')),
                ('band8', models.FloatField(db_column='Band8', default='0.0')),
                ('band8name', models.CharField(blank=True, db_column='Band8Name', default='Band #8', max_length=150, null=True)),
                ('band8count', models.FloatField(db_column='Band8Count', default='0.0')),
                ('band8percentage', models.FloatField(db_column='Band8Percentage', default='0.0')),
                ('band9', models.FloatField(db_column='Band9', default='0.0')),
                ('band9name', models.CharField(blank=True, db_column='Band9Name', default='Band #9', max_length=150, null=True)),
                ('band9count', models.FloatField(db_column='Band9Count', default='0.0')),
                ('band9percentage', models.FloatField(db_column='Band9Percentage', default='0.0')),
                ('band10', models.FloatField(db_column='Band10', default='0.0')),
                ('band10name', models.CharField(blank=True, db_column='Band10Name', default='Band #10', max_length=150, null=True)),
                ('band10count', models.FloatField(db_column='Band10Count', default='0.0')),
                ('band10percentage', models.FloatField(db_column='Band10Percentage', default='0.0')),
                ('bandstotalcount', models.FloatField(db_column='BandsTotalCount', default='0.0')),
                ('deliverytype', models.CharField(blank=True, db_column='DeliveryType', max_length=150, null=True)),
                ('deliveryusedescription', models.CharField(blank=True, db_column='DeliveryUseDescription', max_length=150, null=True)),
                ('memodeliverynote1', models.CharField(blank=True, db_column='MemoDeliveryNote1', max_length=150, null=True)),
                ('deliveryownerfirstname', models.CharField(blank=True, db_column='DeliveryOwnerFirstName', max_length=150, null=True)),
                ('deliveryownerlastname', models.CharField(blank=True, db_column='DeliveryOwnerLastName', max_length=150, null=True)),
                ('deliveryownerfullname', models.CharField(blank=True, db_column='DeliveryOwnerFullName', max_length=150, null=True)),
                ('deliveryowneremail', models.CharField(blank=True, db_column='DeliveryOwnerEmail', max_length=150, null=True)),
                ('createby', models.CharField(blank=True, db_column='CreateBy', max_length=150, null=True)),
                ('Susutype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='susume.susutype')),
            ],
        ),
    ]
