# Generated by Django 4.2.15 on 2024-09-27 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('susume', '0005_alter_susume_susutype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='susume',
            name='susutype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='susu_types', to='susume.susutype'),
        ),
    ]
